const styleProps = {
  style: {
    common: {
      font: {
        size: 12,
        family: "Microsoft Yahei",
        color: "#000",
        weight: "500",
      },
      radius: 8,
      border: { color: "#262626", size: 1 },
      row: {
        height: 52,
        bg: {
          even: {
            color: "#f2f2f2",
            img: "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/bg.png",
          },
          odd: { color: "#fff", img: "" },
        },
        hover: { bg: "#fc0", color: "#000" },
        border: { color: "#e4e4e4", size: 1 },
      },
      cell: {
        padding: { t: 5, r: 5, b: 5, l: 5 },
        border: { color: "#d9d9d9", size: 1 },
      },
    },
    header: {
      height: 52,
      bg: { color: "#096dd9", img: "" },
      font: {
        size: 14,
        family: "Microsoft Yahei",
        color: "#fff",
        weight: "bolder",
      },
      row: { border: { color: "#2d2e2f", size: 1 } },
      cell: { border: { color: "#257acf", size: 1 } },
    },
    lock: {
      bg: { color: "#262626", img: "" },
      font: {
        size: 12,
        family: "Microsoft Yahei",
        color: "#fff",
        weight: "500",
      },
      row: { border: { color: "#2d2e2f", size: 1 } },
      cell: { border: { color: "#2d2e2f", size: 1 } },
    },
    highlight: {
      bg: "rgba(0, 0, 0, 0)",
      font: {
        size: 12,
        family: "Microsoft Yahei",
        color: "#ff0808",
        weight: "500",
      },
    },
    warning: {
      bg: "#6f2323",
      color: "#fff",
      border: { color: "#524041", size: 1 },
    },
    dynamic: [
      {
        type: "image",
        label: "图片",
        key: "logo",
        cellWidth: "90px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "text",
        label: "简文本",
        key: "name",
        cellWidth: "60px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "link",
        label: "链接",
        key: "link",
        cellWidth: "80px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "imageText",
        label: "图文",
        key: "tw",
        cellWidth: "80px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "longText",
        label: "长文本",
        key: "email",
        cellWidth: "160px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "multiRowText",
        label: "多行文本",
        key: "word",
        cellWidth: "150px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "text",
        label: "数字",
        key: "order",
        cellWidth: "50px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "bar",
        label: "单进度条",
        key: "bar",
        cellWidth: "160px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: false,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: {
            show: false,
            align: "center",
            width: 30,
            space: 10,
          },
        },
      },
      {
        type: "bar",
        label: "多进度条",
        key: "bars",
        cellWidth: "300px",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
      {
        type: "button",
        label: "操作",
        key: "action",
        cellWidth: "0",
        layout: { header: "center", body: "center" },
        button: [
          {
            name: "删除",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/del2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "查看",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/look2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
          {
            name: "定位",
            size: { w: 40, h: 40 },
            padding: { t: 5, r: 5, b: 5, l: 5 },
            radius: { tl: 5, tr: 5, br: 5, bl: 5 },
            bg: {
              normal: { color: "#fff", img: "#fff" },
              hover: { color: "#1890ff", img: "" },
              active: { color: "#f5222d", img: "" },
            },
            icon: {
              show: true,
              w: 28,
              h: 28,
              space: 0,
              normal:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc1.png",
              active:
                "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/loc2.png",
            },
            border: {
              normal: { color: "#d9d9d9", size: 1 },
              hover: { color: "#1890ff", size: 1 },
              active: { color: "#f5222d", size: 1 },
            },
            font: {
              show: false,
              align: "center",
              normal: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#000",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              hover: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
              active: {
                size: 20,
                family: "Microsoft Yahei",
                color: "#fff",
                weight: "bolder",
                x: 2,
                y: 2,
                blur: 3,
                shadowColor: "rgb(255,255,255,0.5)",
              },
            },
            ripple: { color: "#fff", opacity: 0.5 },
          },
        ],
        link: { hover: "#fc0000", target: "_blank" },
        multiRowText: { lineHeight: 22 },
        longText: { duration: 4 },
        image: { size: { w: 80, h: 40 } },
        imageText: { size: { w: 40, h: 40 } },
        bar: {
          text: {
            show: true,
            width: 60,
            align: "center",
            space: 10,
          },
          bars: {
            height: 16,
            radius: 16,
            bgColor: "#b4b4b4",
            color: { from: "#bfbfbf", to: "#159ab7" },
            border: { color: "#e8e8e8e", size: 1 },
            split: { color: "#fafafa" },
            space: 2,
          },
          num: { show: true, align: "center", width: 30, space: 10 },
        },
      },
    ],
    mapping: [
      {
        key: "tw",
        mapType: "image",
        text: [],
        image: [
          {
            match: "1",
            value:
              "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/1.png",
          },
          {
            match: "2",
            value:
              "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/2.png",
          },
          {
            match: "3",
            value:
              "//resource.datav.aliyun.com/cube/com/@VISIX-UI/vi-table/0.0.14/public/3.png",
          },
        ],
      },
    ],
  },
  props: {
    header: true,
    scroll: "none",
    interval: 3000,
    rowAnimation: true,
  },
};

exports.styleProps = styleProps;
